### ISSUE TITLE
Error on docker-compose up -d

### ISSUE THREAD

**Issue by LoveMeWithoutAll** [tellform/docker_files#1]
I got an error when start docker.
Error message is as follows:

``
WARNING: The ROOT variable is not set. Defaulting to a blank string. 
``
``
ERROR: Couldn't find env file: /home/tellForm/docker_files/.env
``

**Comment by whitef0x0** [comment]
@LoveMeWithoutAll you need to have a .env variable in the docker_files folder.

**Comment by tonyztan** [comment]
@whitef0x0 Are there any instructions on what steps to take in addition to those listed at https://tellform.com/install_docker to get a minimal version working?

The page makes it look like one just need to run the three commands, but in fact it doesn't work.

I do appreciate your work on this project. Thank you.

**Comment by liangxinhui** [comment]
There is a file `.env.dist` in the `install_docker` root path.
You can make your own `.env` based on it.

**Comment by byteme206** [comment]
I have the exact same issue. No matter whether I set the path to the .env as an explicit or implicit location, the `tellform` container throws an error. The problem is specific to the tellform container, as the other containers are successfully creating their data directories in the location specified within `.env`. 

My suspicion is that this was caused by moving the project to use docker-compose and there's a lingering hard-coded path value within that container. Unless I'm misreading how tell form reads its configuration, the default appears to expect the .env file from within the container itself in `tellform/config/config.js`

**Comment by ghost** [comment]
You just check with this command:
$ ls -lah
in directory where docker_files is located.

So, you can copy .env.dist to .env and edit them with your attributes

**Comment by samarkandiy** [comment]
It worked for me! Thanks!

**Comment by andrelung** [comment]
For starters, after you 
`cd docker_files`
run 
`cp .env.dist .env`
